---
name: Demo

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # We need cosign to verify the Minder client
      - uses: sigstore/cosign-installer@v3.6.0

      # Install the Minder client
      - uses: github.com/stacklok/minder-client-installer@latest

      # Use it!
      - run: minder --help