---
name: Demo

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    env:
      MINDER_OFFLINE_TOKEN: ${{ secrets.MINDER_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      # We need cosign to verify the Minder client
      - uses: sigstore/cosign-installer@v3.6.0

      # Install the Minder client
      - uses: stacklok/minder-client-installer@main

      # Use it!
      - name: Login to minder
        run: minder auth offline-token use